import { colors } from './colors';
import { radius } from './scale';

// Flat CSS custom-property names (kebab) → token value. These names are the
// contract the web's Tailwind utilities depend on (e.g. --color-app → `bg-app`,
// --color-line → `border-line`), so keep them stable.
function colorVars(): [string, string][] {
  return [
    ['--color-accent', colors.accent],
    ['--color-on-accent', colors.text.onAccent],
    ['--color-primary', colors.text.primary],
    ['--color-secondary', colors.text.secondary],
    ['--color-tab-active', colors.text.tabActive],

    ['--color-app', colors.bg.app],
    ['--color-surface', colors.bg.surface],
    ['--color-subtle', colors.bg.subtle],
    ['--color-input', colors.bg.input],

    ['--color-line', colors.border.default],

    ['--color-blaze-red', colors.brand.blazeRed],
    ['--color-blaze-cream', colors.brand.blazeCream],
    ['--color-blaze-hairline', colors.brand.blazeHairline],

    ['--color-warn-bg', colors.status.warn.bg],
    ['--color-warn-text', colors.status.warn.text],
    ['--color-danger-bg', colors.status.danger.bg],
    ['--color-danger-text', colors.status.danger.text],
    ['--color-success-bg', colors.status.success.bg],
    ['--color-success-text', colors.status.success.text],
    ['--color-progress-bg', colors.status.progress.bg],
    ['--color-progress-text', colors.status.progress.text],

    ['--color-map-base', colors.map.base],
    ['--color-map-road', colors.map.road],
    ['--color-map-green', colors.map.green],
    ['--color-map-route', colors.map.route],
    ['--color-map-water', colors.map.water],
    ['--color-map-contour', colors.map.contour],

    ['--color-marker-water', colors.marker.water],
    ['--color-marker-refuge', colors.marker.refuge],
    ['--color-marker-viewpoint', colors.marker.viewpoint],
    ['--color-marker-historic', colors.marker.historic],
    ['--color-marker-food', colors.marker.food],

    ['--color-trail-gr', colors.trail.gr],
    ['--color-trail-pr', colors.trail.pr],
    ['--color-trail-sl', colors.trail.sl],

    ['--color-overlay-dark', colors.overlay.dark],
    ['--color-overlay-dark-strong', colors.overlay.darkStrong],
    ['--color-overlay-frosted', colors.overlay.frosted],
    ['--color-overlay-on-image', colors.overlay.onImage],
    ['--color-overlay-on-image-muted', colors.overlay.onImageMuted],
  ];
}

function radiusVars(): [string, string][] {
  return Object.entries(radius).map(([k, v]) => [`--radius-${k}`, `${v}px`]);
}

/**
 * Render the shared colour + radius tokens as a Tailwind v4 `@theme` block.
 * Web imports the generated output (tokens.css) so its design variables come
 * from this one source — never re-typed. Fonts and the content-shell width stay
 * web-only (next/font binding) and live in the app's globals.css.
 */
export function themeCss(): string {
  const lines = [
    '/* GENERATED by @roam/tokens — do not edit. Run `bun run build` in packages/tokens. */',
    '@theme {',
    '  /* Colours */',
    ...colorVars().map(([k, v]) => `  ${k}: ${v};`),
    '',
    '  /* Radius scale */',
    ...radiusVars().map(([k, v]) => `  ${k}: ${v};`),
    '}',
    '',
  ];
  return lines.join('\n');
}
