import { type SeedInput, createMemoryRepo, importPacks } from '@roam/content';
import { useQuery } from '@tanstack/react-query';
import seedJson from '../assets/content/seed.json';

// The content repository for the browsing app — reads the bundled JSON pack generated by
// the pipeline (real GR11 + Aneto), validated at construction (throws on a malformed
// pack). The same RoamRepo interface will later back onto the local store, and the same
// JSON will download into it, without touching screens (§5.2).
export const contentStore = importPacks(seedJson as unknown as SeedInput);
export const contentRepo = createMemoryRepo(contentStore);

/** Resolve an editorial image by id (heroMediaId / mediaId) from the bundled pack. */
export const mediaFor = (id?: string) => (id ? contentStore.media.get(id) : undefined);

const key = (...parts: string[]) => ['content', ...parts];

export const useContinent = (id: string) =>
  useQuery({ queryKey: key('continent', id), queryFn: () => contentRepo.getContinent(id) });
export const useCountry = (id: string) =>
  useQuery({ queryKey: key('country', id), queryFn: () => contentRepo.getCountry(id) });
export const useRegion = (id: string) =>
  useQuery({ queryKey: key('region', id), queryFn: () => contentRepo.getRegion(id) });
export const useCountries = (continentId: string) =>
  useQuery({
    queryKey: key('countries', continentId),
    queryFn: () => contentRepo.listCountries(continentId),
  });
export const useRegions = (countryId: string) =>
  useQuery({
    queryKey: key('regions', countryId),
    queryFn: () => contentRepo.listRegions(countryId),
  });
export const useRegionObjectives = (regionId: string) =>
  useQuery({
    queryKey: key('region-objectives', regionId),
    queryFn: () => contentRepo.listObjectivesByRegion(regionId),
  });

export const useObjectives = () =>
  useQuery({ queryKey: key('objectives'), queryFn: () => contentRepo.listObjectives() });

export const useObjective = (id: string) =>
  useQuery({ queryKey: key('objective', id), queryFn: () => contentRepo.getObjective(id) });

export const useObjectiveSections = (objectiveId: string) =>
  useQuery({
    queryKey: key('sections', objectiveId),
    queryFn: () => contentRepo.listSections(objectiveId),
  });

export const useObjectiveRoutes = (objectiveId: string) =>
  useQuery({
    queryKey: key('routes', objectiveId),
    queryFn: () => contentRepo.listRoutes(objectiveId),
  });

export const useSection = (id: string) =>
  useQuery({ queryKey: key('section', id), queryFn: () => contentRepo.getSection(id) });

export const useSectionStages = (sectionId: string) =>
  useQuery({
    queryKey: key('stages', sectionId),
    queryFn: () => contentRepo.listStages(sectionId),
  });

export const useStage = (id: string) =>
  useQuery({ queryKey: key('stage', id), queryFn: () => contentRepo.getStage(id) });

export const useRoute = (id: string) =>
  useQuery({ queryKey: key('route', id), queryFn: () => contentRepo.getRoute(id) });
