CREATE TABLE "content_blocks" (
	"id" serial PRIMARY KEY NOT NULL,
	"scope_type" text NOT NULL,
	"scope_id" integer NOT NULL,
	"lens" text NOT NULL,
	"block_type" text NOT NULL,
	"title" text,
	"body" text NOT NULL,
	"order_index" integer DEFAULT 0 NOT NULL,
	"season_from" integer,
	"season_to" integer,
	"source" text DEFAULT 'model' NOT NULL,
	"confidence" double precision DEFAULT 0.5 NOT NULL,
	"review_status" text DEFAULT 'draft' NOT NULL,
	"source_refs" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"manual_override" boolean DEFAULT false NOT NULL,
	"last_reviewed_at" timestamp,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "content_media" (
	"id" serial PRIMARY KEY NOT NULL,
	"scope_type" text NOT NULL,
	"scope_id" integer NOT NULL,
	"lens" text,
	"role" text NOT NULL,
	"order_index" integer DEFAULT 0 NOT NULL,
	"storage_key" text NOT NULL,
	"width" integer,
	"height" integer,
	"geo" jsonb,
	"source_site" text NOT NULL,
	"license" text NOT NULL,
	"license_url" text NOT NULL,
	"author" text NOT NULL,
	"attribution_text" text NOT NULL,
	"source_url" text,
	"caption" text,
	"caption_source" text,
	"alt_text" text,
	"review_status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
