// Generate the map blaze sprites (§17.2) — one PNG per distinct trail waymark, rasterized
// from the SAME waymarkSvg() the RN Waymark uses, so map and UI never drift. Driven by the
// trail registry, so a new trail's blaze is generated automatically. Re-run after adding a
// trail; bump MAP_STYLE_VERSION when the set changes (offline packs cache the sprites).
//
//   bun run apps/mobile/scripts/gen-blazes.ts

import { Resvg } from '@resvg/resvg-js';
import { resolveWaymark, symbolKey, waymarkSvg } from '@roam/core';

const BLAZE_DIR = `${import.meta.dir}/../assets/blazes`;
const SIZES: [string, number][] = [
  ['', 28],
  ['@2x', 56],
  ['@3x', 84],
];

// Trail waymarks (mirrors @roam/pipeline TRAIL_DEFS — kept here so this tooling script needs
// no app dependency on the pipeline). Add a trail's osmc:symbol here when you onboard it.
const WAYMARKS = [
  { ref: 'GR11', osmcSymbol: 'red:white:red_lower:11:black', network: 'nwn' },
  { ref: 'GR 10', osmcSymbol: 'red::white_upper:red_lower:10:', network: 'nwn' },
];

const keys = new Set<string>();
for (const w of WAYMARKS) {
  const sym = resolveWaymark({ osmcSymbol: w.osmcSymbol, network: w.network, ref: w.ref }).symbol;
  if (!sym) {
    console.log(`  skip ${w.ref} — no symbol`);
    continue;
  }
  const key = symbolKey(sym);
  if (keys.has(key)) continue;
  keys.add(key);

  const svg = waymarkSvg(sym);
  await Bun.write(`${BLAZE_DIR}/src/blaze-${key}.svg`, svg);
  for (const [suffix, px] of SIZES) {
    const png = new Resvg(svg, { fitTo: { mode: 'width', value: px } }).render().asPng();
    await Bun.write(`${BLAZE_DIR}/blaze-${key}${suffix}.png`, png);
  }
  console.log(`  ✓ blaze-${key} (${w.ref})`);
}

const sorted = [...keys].sort();
const lines = sorted
  .map((k) => `  'blaze-${k}': require('../../assets/blazes/blaze-${k}.png'),`)
  .join('\n');
const file = `// Pre-rendered blaze sprites — GENERATED by apps/mobile/scripts/gen-blazes.ts from the
// trail registry waymarks (§17.2). One sprite per distinct osmc:symbol, named
// blaze-<symbolKey>. Re-run after adding a trail; bump MAP_STYLE_VERSION when this set
// changes (offline packs cache the sprites). Registered on the map by <MapImages>.
export const BLAZE_SPRITES = {
${lines}
} as const;
`;
await Bun.write(`${import.meta.dir}/../components/map/blazeIcons.tsx`, file);
console.log(`\n✓ wrote blazeIcons.tsx — ${sorted.length} sprites`);
