import { type OsmcSymbol, waymarkSvg } from '@roam/core';

// The painted trail blaze, reconstructed on the web from the parsed osmc:symbol
// using the exact same pure renderer (@roam/core waymarkSvg) the app, map and
// legend use — so the sign never drifts across surfaces (§17.8). GR11's
// `red:white:red_lower:11:black` renders as a white plate with a red lower bar
// and "11".
export function Waymark({ symbol, size = 28 }: { symbol: OsmcSymbol; size?: number }) {
  const svg = waymarkSvg(symbol, { fontFamily: 'var(--font-geist-mono), monospace' });
  return (
    <span
      className="inline-block shrink-0 overflow-hidden rounded-[3px]"
      style={{ width: size, height: size }}
      role="img"
      aria-label="Trail waymark"
      // The SVG is generated by our own pure function from structured data — no
      // user input flows into it, so this is safe.
      // biome-ignore lint/security/noDangerouslySetInnerHtml: own-generated SVG sprite, no user input
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
