// Pre-rendered blaze sprites — GENERATED by apps/mobile/scripts/gen-blazes.ts from the
// trail registry waymarks (§17.2). One sprite per distinct osmc:symbol, named
// blaze-<symbolKey>. Re-run after adding a trail; bump MAP_STYLE_VERSION when this set
// changes (offline packs cache the sprites). Registered on the map by <MapImages>.
export const BLAZE_SPRITES = {
  'blaze-white-red-lower-11': require('../../assets/blazes/blaze-white-red-lower-11.png'),
  'blaze-white-upper-red-lower-10': require('../../assets/blazes/blaze-white-upper-red-lower-10.png'),
} as const;
